# Generated by Django 5.1.4 on 2026-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripevent',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='recap_70hr',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_miles',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tripevent',
            name='mile_marker',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='cycle_hours_used',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='tripevent',
            index=models.Index(fields=['trip', 'start_time'], name='trips_tripe_trip_id_f07920_idx'),
        ),
    ]
